import{S as b,a as v}from"./assets/vendor-2591be5d.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const f=new b(".gallery a",{overlayOpacity:8,captionData:"href",captionDelay:250,captionClass:"text-center"}),d=document.querySelector(".gallery"),c=document.querySelector(".form"),l=document.querySelector(".load-btn");c.addEventListener("submit",L);l.addEventListener("click",x);const o=document.getElementById("loader");let p=1,y=15;o.style.display="none";async function L(a){a.preventDefault();const r=c.querySelector("input[type='text']").value;o.style.display="inline-block",d.innerHTML="";try{const{hits:n,totalHits:e}=await m(r);n.length===0||e<=0?(o.style.display="none",l.style.display="none",u('<i class="fa-solid fa-xmark"></i>Sorry, there are no images matching your search query. Please try again!')):n.length<=y&&(d.insertAdjacentHTML("beforeend",h(n)),f.refresh(),p++,l.style.marginBottom="50px",l.style.display="block")}catch{}finally{o.style.display="none",c.reset()}}async function x(){try{o.style.display="flex",o.style.position="fixed",o.style.bottom="0",o.style.left="50%",o.style.transform="translateX(-50%)";const{hits:a,totalPages:t}=await m(c.querySelector("input[type='text']").value);p>=t?(l.style.display="none",u(`<i class="fa-solid fa-xmark"></i>We're sorry, but you've reached the end of search results.`)):(d.insertAdjacentHTML("beforeend",h(a)),f.refresh(),p++);const r=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{u(`<i class="fa-solid fa-xmark"></i>We're sorry, but you've reached the end of search results.`),l.style.display="none"}finally{o.style.display="none"}}const w="43197174-dcc5f5044572d8f441379a766";async function m(a){const t=new URLSearchParams({key:w,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y,page:p}),r=await v.get(`https://pixabay.com/api/?${t}`);console.log(r);const{hits:n,totalHits:e}=r.data,s=Math.ceil(e/y);return{hits:n,totalHits:e,totalPages:s}}function h(a){return a.map(({webformatURL:t,largeImageURL:r,tags:n,likes:e,views:s,comments:i,downloads:g})=>`   
        <li class="list-item">
        <a class="gallery-link" href="${r}">
            <img  class="list-image" src="${t}" alt="${n}">
            <div class="image-details">          
                <p class="likes"><span class="span">Likes:</span><br> <span class="span-link">${e}</span> </p>
                <p class="views"><span class="span">Views:</span><br> <span class="span-link">${s}</span>  </p>                                
                <p class="comments"><span class="span">Comments:</span><br> <span class="span-link">${i}</span></p>               
                <p class="downloads"><span class="span">Downloads:</span><br> <span class="span-link">${g}</span></p>                           
            </div>
        </li>`).join("")}let M=document.getElementById("toastBox");function u(a){let t=document.createElement("div");t.classList.add("toast"),t.innerHTML=a,M.appendChild(t),setTimeout(()=>{t.remove()},3e3)}
//# sourceMappingURL=commonHelpers.js.map
