import{S as g,a as b}from"./assets/vendor-2591be5d.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const u=new g(".gallery a",{overlayOpacity:8,captionData:"href",captionDelay:250,captionClass:"text-center"}),p=document.querySelector(".gallery"),c=document.querySelector(".form"),i=document.querySelector(".load-btn");c.addEventListener("submit",L);i.addEventListener("click",x);const n=document.getElementById("loader");let y=1,v=15;n.style.display="none";async function L(a){a.preventDefault();const r=c.querySelector("input[type='text']").value;n.style.display="inline-block",p.innerHTML="";try{const{hits:o}=await f(r);o.length===0?(n.style.display="none",i.style.display="none",d('<i class="fa-solid fa-xmark"></i>Sorry, there are no images matching your search query. Please try again!')):(p.insertAdjacentHTML("beforeend",m(o)),u.refresh(),y++,n.style.display="none",i.style.marginBottom="50px",i.style.display="block")}catch{}finally{n.style.display="none",c.reset()}}async function x(){try{n.style.display="flex",n.style.position="fixed",n.style.bottom="0",n.style.left="50%",n.style.transform="translateX(-50%)";const{hits:a}=await f(c.querySelector("input[type='text']").value);a.length===0?(i.style.display="none",d(`<i class="fa-solid fa-xmark"></i>We're sorry, but you've reached the end of search results.`)):(p.insertAdjacentHTML("beforeend",m(a)),u.refresh(),y++);const s=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch{d(`<i class="fa-solid fa-xmark"></i>We're sorry, but you've reached the end of search results.`)}finally{n.style.display="none"}}const w="43197174-dcc5f5044572d8f441379a766";async function f(a){const s=new URLSearchParams({key:w,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:y});return(await b.get(`https://pixabay.com/api/?${s}`)).data}function m(a){return a.map(({webformatURL:s,largeImageURL:r,tags:o,likes:e,views:t,comments:l,downloads:h})=>`   
        <li class="list-item">
        <a class="gallery-link" href="${r}">
            <img  class="list-image" src="${s}" alt="${o}">
            <div class="image-details">          
                <p class="likes"><span class="span">Likes:</span><br> <span class="span-link">${e}</span> </p>
                <p class="views"><span class="span">Views:</span><br> <span class="span-link">${t}</span>  </p>                                
                <p class="comments"><span class="span">Comments:</span><br> <span class="span-link">${l}</span></p>               
                <p class="downloads"><span class="span">Downloads:</span><br> <span class="span-link">${h}</span></p>                           
            </div>
        </li>`).join("")}let S=document.getElementById("toastBox");function d(a){let s=document.createElement("div");s.classList.add("toast"),s.innerHTML=a,S.appendChild(s),setTimeout(()=>{s.remove()},3e3)}
//# sourceMappingURL=commonHelpers.js.map
